### ISSUE TITLE
Milestone 1 Review 

### ISSUE THREAD

**Issue by quangogster** [quangogster/todd-app#1]
###  General 
- Adapt React-Boilerplate to Theme Layout

### End Result Components
Extending react-bootstrap components and functionality.
Modify React-Boilerplate to use react-bootstrap. (remove javascript from template) 

####  Left Sidebar 
- Sidebar Layout Component
- Recent Conversation Component
- Contact Component
- Dummy Search Component

####  Chat 
- Chat Layout Component
- Chat Header Component
- Message Component
  * Self
  * Friend
- Dummy Compose Component

####  Right Sidebar Component 
- Sidebar Layout Component
- Profile Card Component
- Gallery Component

#### Total price: $500

**Comment by quangogster** [comment]
Hey @tzusman! Glad you could make it here.  Can you review this Milestone and give me an approval to start?

**Comment by quangogster** [comment]
Also @tzusman, do you have the license/files for the Beagle theme?

**Comment by tzusman** [comment]
[Download link for theme](https://dl.dropboxusercontent.com/u/9122345/beagle-theme.zip)

**Comment by tzusman** [comment]
> Modify React-Boilerplate Header Component to theme's look
Not sure what that means.

If you clone the react-boilerplate and run `npm run clean`, then there should be a blank slate.

**Comment by quangogster** [comment]
I made a small mistake.  I have changed it to : 

> Modify React-Boilerplate to use react-bootstrap. (remove javascript from template)

**Comment by tzusman** [comment]
looks good then!

**Comment by quangogster** [comment]
Great!  todd-app is ready to take off.

**Comment by quangogster** [comment]
@tzusman, I'm doing the development in Gitlab.  I will mirror this repo on every merge to master.
