### ISSUE TITLE
react-icons named imports

### ISSUE THREAD

**Issue by danielr18** [quangogster/todd-app#3]
@tzusman In order to achieve something like this: `import { MdSearch, MdLink } from 'react-icons/md';` we would need to run babel on react-icons as it uses ES6, which I did to try. 

Results were: webpack initial building time passed from 9 seconds to 30. Small change from 200ms to 2 seconds.

I don't think we should take this performance loss just to save a few lines of code, but let me know your opinion.

**Comment by tzusman** [comment]
you are correct.  that's crazy about the change in build times.
